<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'exam/test/take'  => __DIR__ . '/view/exam/test/take.phtml',
    'exam/test/list'  => __DIR__ . '/view/exam/test/list.phtml',
    'exam/test/index' => __DIR__ . '/view/exam/test/index.phtml',
);
